CREATE TABLE Users (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	HWID NVARCHAR(64) NOT NULL,
	IP NVARCHAR(32) NOT NULL
)

CREATE TABLE Links (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	UserId INT FOREIGN KEY REFERENCES Users(Id),
	OriginalUrl NVARCHAR(2048) NOT NULL,
	ShortenedUrl NVARCHAR(64) NOT NULL,
	CreationDate DATETIME NOT NULL
)

CREATE TABLE Requests (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	LinkId INT FOREIGN KEY REFERENCES Links(Id),
	UserId INT FOREIGN KEY REFERENCES Users(Id),
	RequestDate DATETIME NOT NULL
)